### ISSUE TITLE
Add 48hr response rate benchmark to ecosystem dashboard

### ISSUE THREAD

**Issue by momack2** [ipfs-shipyard/ecosystem-research#6]
Would it be possible to update our ecosystem dashboard to include a count + list of PRs/issues created in the past week that didn’t get a response/action within the first 48hrs? Seems like this would be an improved view over devstats for tracking whether we’re meeting the ecosystem support KPI @hsanjuan specified for all community PRs/issues get a response within 48hrs.

**Comment by andrew** [comment]
So for this I'll need to download the events for each Issue and calculate the time between opening and either closing (if it's less than 48 hours) or first event date.

Then we can list, count and graph the number of events where that time is greater than 48 hours.

One thing we might want to do is define what is considered an acceptable response type. For instance, if a non-PL person comments, does that count? Or if a bot automatically labels issues, does that count.

For now I'll filter the events where the actor is a PL person.

I'll also initially focus on measuring and recording this from now rather than going back and calculating it for all historical issues, we can back fill later if required.

**Comment by andrew** [comment]
First simple pass is live here: https://ecosystem-research.herokuapp.com/slow_response

![Screenshot 2020-04-24 at 12 09 01](https://user-images.githubusercontent.com/1060/80206622-90880780-8624-11ea-9118-f544ce99914f.png)

Basically looks for anything that hasn't been closed or commented on within 48 hours. Doesn't into take account who commented (PL or not) or other events like label, referencing etc.

It also ignores any issues and PRs that haven't been open for more than 48 hours since there's still a chance for them to be responded to before the window closes.

**Comment by andrew** [comment]
Now syncing the "first_response_at" for recent issues, so it includes actions like labelling, reviewing, requesting reviews etc (almost event event listed here: https://developer.github.com/v3/issues/timeline/) from PL employees.

![Screenshot 2020-04-27 at 15 28 12](https://user-images.githubusercontent.com/1060/80383938-25486a80-889c-11ea-9ef2-26968baecd39.png)

Will demo at the collabs call later today: http://ecosystem-research.herokuapp.com/slow_response

**Comment by andrew** [comment]
One edge case that isn't really covered here are repos that exist on our orgs that are mainly worked on by non-PL folk, for example: https://github.com/libp2p/jvm-libp2p

![Screenshot 2020-04-27 at 16 27 41](https://user-images.githubusercontent.com/1060/80390327-3006fd80-88a4-11ea-998a-443470576b74.png)

The PR didn't have a response from a PL person within 48 hours, but also didn't really need one, as we don't really maintain that repo. 

Question is, do we include it in the slow response metrics, or exclude certain repos or some other thing?

**Comment by hsanjuan** [comment]
We need to be able to filter per organization at least. My efforts are focused on the IPFS organization only for the moment, therefore putting libp2p, ipld, multiformats, shipyard on the mix will not give me overly valuable information.

In IPFS, if a repo is not worked by PL folk (or core-team folk), it should probably be in ipfs-shipyard. But in the case of a libp2p repo, how they interpret those issues should be up to them since there is no shipyard-equivalent.

**Comment by andrew** [comment]
@hsanjuan I've added in the same filters as on the other pages now: https://ecosystem-research.herokuapp.com/slow_response?org=ipfs

**Comment by hsanjuan** [comment]
Thanks!

One problem I see is that if an issue lands of Friday and is answered on Monday, it is still "slow". Ideally, it should skip weekends from the calculation...

Another thing on my wish list would be to be able to zoom out to see 3 months, 6 months, 1 year...

**Comment by andrew** [comment]
Historical data will take a little time to download due to rate limits but shouldn't be too hard to do.

Ignoring weekends in the sql query could get messy but I can just precalculate the "response within 48 business hours?" flag and write it to the db.

**Comment by andrew** [comment]
Note to self, handy gem for time calculations taking business hours into account: https://github.com/Intrepidd/working_hours

**Comment by momack2** [comment]
Our goal is to answer all inbound issues within 48 hrs - so our goal would be for this list to be empty. To make that possible, seems like the ability to show the inbox of what isn't yet 48 hrs old but doesn't have a response yet would be an important view. Maybe could do as a toggle or filter to "show within last 48hrs" or something?

**Comment by andrew** [comment]
@momack2 you can already see an inbox view of everything that's not had a response yet here: https://ecosystem-research.herokuapp.com/all?exclude_employees=true&no_milestone=true&recent=true&state=open&uncommented=true&unlabelled=true  

I believe @hsanjuan is already using that for his triage

**Comment by hsanjuan** [comment]
> I believe @hsanjuan is already using that for his triage

I know this exists but I am actually swamped. I read and answer as much as I can from the things that I'm subscribed to and I haven't been able to check this recently (I was also waiting to archive many and move them out of the way).

@andrew now that new issues are labelled automatically with "need/triage" in most places, we will need to adapt the unlabelled filter. No labels is as bad as need/triage.

**Comment by andrew** [comment]
@hsanjuan I've added a graph of the weekly avg response rate on the IPFS org for the past year, your efforts have really been paying off!

![Screenshot 2020-04-29 at 17 16 00](https://user-images.githubusercontent.com/1060/80620437-ee11bf00-8a3d-11ea-8c33-403558e712b6.png)

Some other rejected graphs:

Avg response time across all 6 PL orgs over the past year: 
![Screenshot 2020-04-29 at 16 40 21](https://user-images.githubusercontent.com/1060/80620520-0550ac80-8a3e-11ea-9818-3d12fd889ff7.png)

Same but one line per PL org:
![Screenshot 2020-04-29 at 17 12 41](https://user-images.githubusercontent.com/1060/80620573-14cff580-8a3e-11ea-80aa-4eb10e859bc8.png)

**Comment by andrew** [comment]
> @andrew now that new issues are labelled automatically with "need/triage" in most places, we will need to adapt the unlabelled filter. No labels is as bad as need/triage.

Will update the "unlabelled" filter to include that label. Although now it's recording the "time to first response", we could just have a filter that says "no response from PL yet"

**Comment by andrew** [comment]
Added a new filter called "No PL response" which should work better than "no label+no comment+no milestone" now that we have bots and automatic labels: https://ecosystem-research.herokuapp.com/all?exclude_employees=true&no_response=true&recent=true

**Comment by andrew** [comment]
I'm going to close this out now as I believe all the pieces are in place.
